### PR TITLE
Fix out-of-order-load warnings

### LINKED ISSUE #575: unsorted-dict-items & out-of-order-load not autofixed by buildifier?
I'm using buildifier: 0.22.0

When I run buildifier on my code, it doesn't change the load order or the dict items. After the buildifier autoformat, when I run buildifier with --lint=warn and these warnings turned on, it complains about them. The README suggests these issues should be autofixed.

To reproduce:
Download bazelbuild/bazel-toolchains at commit 09c26bd109b44be2faecab77378a001d9bed3886

Run buildifier 0.22.0 on configs/dependency-tracking/ubuntu1604.bzl configs/ubuntu16_04_clang/9.0.0/bazel_0.23.1/cc/cc_toolchain_config.bzl

run buildifier with --lint=warn --warnings=unsorted-dict-items,out-of-order-load configs/dependency-tracking/ubuntu1604.bzl  configs/ubuntu16_04_clang/9.0.0/bazel_0.23.1/cc/cc_toolchain_config.bzl

You should see
```
configs/ubuntu16_04_clang/9.0.0/bazel_0.23.1/cc/BUILD:49: unsorted-dict-items: Dictionary items are out of their lexicographical order.
configs/ubuntu16_04_clang/9.0.0/bazel_0.23.1/cc/BUILD:50: unsorted-dict-items: Dictionary items are out of their lexicographical order.
configs/ubuntu16_04_clang/9.0.0/bazel_0.23.1/cc/BUILD:51: unsorted-dict-items: Dictionary items are out of their lexicographical order.
configs/ubuntu16_04_clang/9.0.0/bazel_0.23.1/cc/BUILD:125: out-of-order-load: Load statement is out of its lexicographical order.
configs/ubuntu16_04_clang/9.0.0/bazel_0.23.1/cc/cc_toolchain_config.bzl:31: out-of-order-load: Load statement is out of its lexicographical order.
configs/ubuntu16_04_clang/9.0.0/bazel_0.23.1/cc/cc_toolchain_config.bzl:1735: unsorted-dict-items: Dictionary items are out of their lexicographical order.
```

### PR DESCRIPTION
**Pull request by vladmos**
If buildifier applies `out-of-order-load` without applying `load-on-top` (either because of the flags or because "load-on-top" is not enabled for BUILD files), it may occur that there are other statements between load statements that depend on the first load, and swapping the loads lead to a breaking change:

    load(":b.bzl", "b")
    b()
    load(":a.bzl", "a")

With this update buildifier only sorts consequent chunks of load statements (i.e. load statements without other statements between them). Comments between the load statements are fine as long as they belong to one of the load statements, the following will be sorted:

    load(":b.bzl", "b")
    # after-comment for b
    
    # before-comment for a
    load(":a.bzl", "a")

The following will not be sorted:

    load(":b.bzl", "b")

    # standalone comment

    load(":a.bzl", "a")

Fixed #575

### CODE REVIEW

File: warn/warn_cosmetic.go [hunk 1]
```diff
@@ -124,80 +124,104 @@ func loadOnTopWarning(f *build.File, fix bool) []*Finding {
...
 
-func outOfOrderLoadWarning(f *build.File, fix bool) []*Finding {
-	findings := []*Finding{}
+// compareLoadLabels compares two module names
+func compareLoadLabels(load1Label, load2Label string) bool {
+	// handle absolute labels with explicit repositories separately to
+	// make sure they preceed absolute and relative labels without repos
+	isExplicitRepo1 := strings.HasPrefix(load1Label, "@")
+	isExplicitRepo2 := strings.HasPrefix(load2Label, "@")
+	if isExplicitRepo1 == isExplicitRepo2 {
```
Comment (laurentlb) [inline warn/warn_cosmetic.go]: reverse condition to remove indentation

File: warn/warn_cosmetic.go [hunk 2]
```diff
@@ -124,80 +124,104 @@ func loadOnTopWarning(f *build.File, fix bool) []*Finding {
...
+		// Either both labels have explicit repository names or both don't, compare their packages
+		// and break ties using file names if necessary
 
-	if f.Type == build.TypeWorkspace {
-		// Not applicable for WORKSPACE files
-		return findings
-	}
+		module1Parts := strings.SplitN(strings.TrimLeft(load1Label, "@"), ":", 2)
```
Comment (laurentlb) [inline warn/warn_cosmetic.go]: Is it useful to trim "@"?

File: warn/warn_cosmetic.go [hunk 3]
```diff
@@ -124,80 +124,104 @@ func loadOnTopWarning(f *build.File, fix bool) []*Finding {
 	return findings
 }
 
-func outOfOrderLoadWarning(f *build.File, fix bool) []*Finding {
-	findings := []*Finding{}
+// compareLoadLabels compares two module names
+func compareLoadLabels(load1Label, load2Label string) bool {
+	// handle absolute labels with explicit repositories separately to
+	// make sure they preceed absolute and relative labels without repos
```
Comment (laurentlb) [inline warn/warn_cosmetic.go]: typo: precede

File: warn/warn_cosmetic.go [hunk 4]
```diff
@@ -124,80 +124,104 @@ func loadOnTopWarning(f *build.File, fix bool) []*Finding {
 	return findings
 }
 
-func outOfOrderLoadWarning(f *build.File, fix bool) []*Finding {
-	findings := []*Finding{}
+// compareLoadLabels compares two module names
+func compareLoadLabels(load1Label, load2Label string) bool {
```
Comment (laurentlb) [inline warn/warn_cosmetic.go]: Add examples/explanation in a comment to show how it differs from alphanumeric sort (is it just about the prefix "@"?)

File: warn/warn_cosmetic.go (hunk 1 above)
Comment (vladmos) [reply warn/warn_cosmetic.go]: Done.

File: warn/warn_cosmetic.go (hunk 2 above)
Comment (vladmos) [reply warn/warn_cosmetic.go]: I've just fixed the code written by someone else, but it seems that it can be removed.

File: warn/warn_cosmetic.go (hunk 3 above)
Comment (vladmos) [reply warn/warn_cosmetic.go]: Done.

File: warn/warn_cosmetic.go (hunk 4 above)
Comment (vladmos) [reply warn/warn_cosmetic.go]: Done.
