### PR TITLE
Fix 'unitialized' warnings for nested functions and comprehensions

### LINKED ISSUE #926: Buildifier confused about return values in nested methods
eg:
```
def outer():
  def inner():
    return 0

  i = inner()
```

Buildifier throws the following error on that code snippet:
return-value: Some but not all execution paths of "outer" return a value

But what executions of outer() have a return value? I would suspect that that's safe/valid starlark, but buildifier thinks otherwise?

### PR DESCRIPTION
**Pull request by vladmos**
Fixes #926

### CODE REVIEW

File: warn/warn_control_flow.go [hunk 1]
```diff
@@ -421,6 +421,7 @@ func unusedVariableCheck(f *build.File, root build.Expr) (map[string]bool, []*Li
 		case *build.LoadStmt:
 			// LoadStmt nodes store the loaded symbols as idents, even though in the
 			// source code they are strings. These idents may confuse the check,
+			// source code they are strings. These idents may confuse the check,
```
Comment (meisterT) [inline warn/warn_control_flow.go:424]: accidental copy?

**Review by meisterT — APPROVED** [review]
