### PR TITLE
Fix wrong unitialized warnings

### LINKED ISSUE #549: uninitialized false positive between struct fields and future variables.
Given:

```python
# testing.bzl
"""module comment"""

def foo(
    something = False):
    """Declares output files (and optional output file map) for a compile action.

    Args:
        something: a boolean

    Returns:
        A `struct`
    """
    if not something:
        return struct(
            abc = [],
        )
    
    abc = ["something"]

    return struct(
        abc = abc,
    )
```

Results in:

```
testing.bzl:15: uninitialized: Variable "abc" may not have been initialized. (https://github.com/bazelbuild/buildtools/blob/master/WARNINGS.md#uninitialized)
```

That's the first return getting the error, it see the `abc` with the struct as the problem.

### PR DESCRIPTION
**Pull request by vladmos**
Fixes #549

Workaround for #550: the check is temporarily disabled for comprehensions.

### CODE REVIEW

File: warn/warn_control_flow.go [hunk 1]
```diff
@@ -376,14 +376,33 @@ func findUninitializedVariables(stmts []build.Expr, previouslyInitialized map[st
 	// findUninitializedIdents traverses an expression (simple statement or a part of it), and calls
 	// `callback` on every *build.Ident that's not mentioned in the map of initialized variables
 	findUninitializedIdents := func(expr build.Expr, callback func(ident *build.Ident)) {
+		// Collect lValues, they shouldn't be taken into account
+		// For example, if the expression is `a = foo(b = c)`, only `c` can be an unused variable here.
+		lValues := make(map[*build.Ident]bool)
 		build.Walk(expr, func(expr build.Expr, stack []build.Expr) {
-			if ident, ok := expr.(*build.Ident); ok && !initialized[ident.Name] {
+			if bin, ok := expr.(*build.BinaryExpr); ok && bin.Op == "=" {
```
Comment (laurentlb) [inline warn/warn_control_flow.go]: It would be useful to have an AssignStmt in the future, to avoid this kind of confusion.

File: warn/warn_control_flow_test.go [hunk 2]
```diff
@@ -669,4 +669,57 @@ def foo():
...
+
+	checkFindings(t, "uninitialized", `
+def f():
+    if foo:
+        x = foo
+
+    f(x = y)
+`,
+		[]string{},
+		scopeEverywhere)
```
Comment (laurentlb) [inline warn/warn_control_flow_test.go]: Add test:

```
if True:
  f(x = 3)
else:
  x = 3
print(x)  # warning
```

File: warn/warn_control_flow.go (hunk 1 above)
Comment (vladmos) [reply warn/warn_control_flow.go]: I agree, but this case also covers assignment expressions (as for keyword arguments). Buildifier should warn about uninitialized `x` in `f(x = y)`.

Perhaps I'll create an AssignmentExpr node (we don't have separate statements nodes anyway).

File: warn/warn_control_flow_test.go (hunk 2 above)
Comment (vladmos) [reply warn/warn_control_flow_test.go]: Done.

File: warn/warn_control_flow.go (hunk 1 above)
Comment (laurentlb) [reply warn/warn_control_flow.go]: In `f(x = y)`, we shouldn't warn about x, only y.
